# ==========================
# Server Configuration
# ==========================

server.port=7070

# ==========================
# PostgreSQL Configuration
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=1432578@Yeshu

# ==========================
# JPA Configuration
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================
# Eureka Client Configuration
# ==========================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ==========================
# Logging
# ==========================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jackson.deserialization.fail-on-unknown-properties=true


# ==========================
# Actuator Configuration
# ==========================

management.endpoints.web.exposure.include=health,info,refresh

management.endpoint.health.show-details=always
